api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "cutlery-bundle-2"
type = "function"
uid = "b68d39ce-f0be-ab92-dc74-d0c5c6fc4bd6c12de3e3"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
